users:
  name:
    length:
      maximum: 50
  email:
    length:
      maximum: 255
  password:
    length:
      minimum: 6
  age:
    lwr_bound: 0
microposts:
  content:
    length:
      maximum: 140
  picture:
    size:
      max_vol: 5
